### ISSUE TITLE
问题报告 | Bug report 

### ISSUE THREAD

**Issue by wangzhiyonglyk** [zyronon/douyin#103]
**第一个问题：刷新判断有误** 
![image](https://github.com/user-attachments/assets/34341477-2d91-4030-931e-5f8deefeb315)

这里应该是小于等于 （<=) ，因为当加载第一页数据后，立马下拉刷新，这个时候新旧数据长度是一样的，如果是小于就无法刷新了。

**第二个问题：事件监听地方有误**

![image](https://github.com/user-attachments/assets/4edcf4e1-fb75-4b8f-b04a-0a25fdd232f9)

这里应该要单独监听localIndex变化，并且这个监听中去Emit事件，防止父组件没有使用v-model指令

**第三个问题：如果父组件强行更的Index不在当前范围怎么办**

![image](https://github.com/user-attachments/assets/e6416fb4-5a24-41f2-af4b-58edde4cd3d2)

**解决方案如下**
父组件改变下标时，这里应该做滑动判断，滑动到指定的节点，如果下标不在当前渲染的节点的，应该要重新初始化 代码如下
![image](https://github.com/user-attachments/assets/86efa62e-6259-4c99-8599-3eea7a62ba61)

第四个问题：
![image](https://github.com/user-attachments/assets/4d4e9ed4-f8b2-420a-b982-460eac90d4e8)

还有这里half计算也不对，按这种计算，如果虚拟列表长度为奇数，就会有问题，应该取整

第五个问题：
另外上下滑动的时候，会产生声音重叠现象，光用单击事件来暂停不够的，应该要有一个定时器去监听。

**Comment by zyronon** [comment]
好的，已合并
