### ISSUE TITLE
功能请求 | 开发后端或者整个后端管理员登录界面和普通用户注册\登录界面

### ISSUE THREAD

**Issue by Mulali** [zyronon/douyin#106]
作者能不能整个后端管理员界面管理用户数据、可以发评论或者同步抖音、快手等视频平台账号或者登录，最近想拿服务器部署MySQL还有Docker就需要添加这些功能

**Comment by xubaobao19940428** [comment]
........这样的话和那些自动化的工具有什么区别

**Comment by xubaobao19940428** [comment]
> 作者能不能整个后端管理员界面管理用户数据、可以发评论或者同步抖音、快手等视频平台账号或者登录，最近想拿服务器部署MySQL还有Docker就需要添加这些功能

........这样的话和那些自动化的工具有什么区别

**Comment by GIS142857** [comment]
> 作者能不能整个后端管理员界面管理用户数据、可以发评论或者同步抖音、快手等视频平台账号或者登录，最近想拿服务器部署MySQL还有Docker就需要添加这些功能


我用 Go 开发了后端，可以看看我的项目https://github.com/GIS142857/douyin-backend.git

**Comment by zyronon** [comment]
https://github.com/zyronon/douyin/issues/123

https://github.com/zyronon/douyin/issues/118
