### ISSUE TITLE
问题报告 | Bug report  下载仓库的文件大小令人吃惊 项目700MB

### ISSUE THREAD

**Issue by you-hengh** [zyronon/douyin#111]
1. 描述
  1.1 仓库的文件大小令人吃惊 项目700MB, 请开发者确认一下实际项目是否真的这么大(尚未安装依赖项)
  1.2 public的图片后缀格式全部错误, 具体如下图所示, 请确认图片真实格式

2. 截图
根目录:
![2024-09-20_10-21-43](https://github.com/user-attachments/assets/823aae02-cb59-4528-9117-6a3b2e92f36d)
最大占用:
![2024-09-20_10-22-21](https://github.com/user-attachments/assets/6202fac9-d071-4e62-8def-df64d2d957e2)
public 占用:
![2024-09-20_10-24-07](https://github.com/user-attachments/assets/a7759d27-5d2d-4963-a8f6-9baf02831ac4)
图像格式错误:
![2024-09-20_10-32-52](https://github.com/user-attachments/assets/638e7b72-217c-47f9-b82c-7ecd0d61aecb)

**Comment by zyronon** [comment]
1、git文件大很正常啊，提交了几百上千次
2、图片后缀是错误的，方便使用统一改的png

实际打包出来的文件只有几M大小
