### ISSUE TITLE
用的哪个前端组件库?

### ISSUE THREAD

**Issue by lijianbo2004** [zyronon/douyin#114]

**Comment by zyronon** [comment]
全自己画

**Comment by elarber** [comment]
我感觉[sard-uniapp](https://sutras.github.io/sard-uniapp-docs/#/guide/intro)挺好用的

**Comment by zyronon** [comment]
> 我感觉[sard-uniapp](https://sutras.github.io/sard-uniapp-docs/#/guide/intro)挺好用的

没用过🤣
