### ISSUE TITLE
功能请求 | Feature request  如何获取抖音视频的video_id？

### ISSUE THREAD

**Issue by jeffreyrobeson** [zyronon/douyin#122]
1、描述
请尽可能详细描述您需要的特性。
  如何获取抖音视频的video_id？
2、这个功能解决了什么问题？
请尽可能详尽地说明这个需求的用例和场景

1. Description
Please provide as detailed a description as possible of the features you need.

2. What problem does this feature solve?
Please provide as detailed a description of the use cases and scenarios for this requirement as possible

**Comment by GIS142857** [comment]
video_id 就是 aweme_id

**Comment by zyronon** [comment]
![image](https://github.com/user-attachments/assets/e661d009-132d-48a9-bd7b-5a858aabd360)

直接打开抖音的PC web版，f12看请求撒

**Comment by jeffreyrobeson** [comment]
> video_id 就是 aweme_id

"aweme_id": "7260749400622894336",
https://www.douyin.com/aweme/v1/play/?video_id=v0d00fg10000cj1lq4jc77u0ng6s1gt0&line=0
aweme_id不是video_id吧？
