### ISSUE TITLE
问题报告 | Bug report 

### ISSUE THREAD

**Issue by denghua1983** [zyronon/douyin#124]
git clone 执行出现异常

hua@huadeMacBook-Pro douyin % npm install
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: douyin-vue@1.1.0
npm error Found: vue@3.4.21
npm error node_modules/vue
npm error   vue@"3.4.21" from the root project
npm error
npm error Could not resolve dependency:
npm error peer vue@"^2.6.14 || ^3.5.11" from pinia@2.2.6
npm error node_modules/pinia
npm error   pinia@"^2.1.7" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error

**Comment by abcdedfdfasdfsa** [comment]
npm install
是执行这个命令时报错吗？

**Comment by zyronon** [comment]
![image](https://github.com/user-attachments/assets/dc2bdd03-33fd-40d4-a0c9-024474166edc)

刚试了一下，是可以正常clone的，你看下是不是你的网络有问题？

或者使用gitee的地址进行clone 

git clone https://gitee.com/zyronon/douyin.git (中国使用)
