### ISSUE TITLE
苹果手机 不能正常打开

### ISSUE THREAD

**Issue by tea3300** [zyronon/douyin#24]
你好 这套代码发现在苹果手机 不能正常打开
效果样式丢失  请问如何解决？？谢谢

**Comment by zyronon** [comment]
注意：安卓手机请用[Via手机浏览器](https://viayoo.com/zh-cn/)或者Chrome浏览器手机版本预览。其他浏览器检测到页面内有视频会强制将视频全屏，并显示控制按钮，导致css和js都失效
