### ISSUE TITLE
有考虑提供本地化的视频接口吗？

### ISSUE THREAD

**Issue by FQFQFQFQ** [zyronon/douyin#26]
有考虑提供本地化的视频接口吗？

**Comment by zyronon** [comment]
什么意思？不加载网络视频？

**Comment by FQFQFQFQ** [comment]
我发现Git上有大量的抖音视频爬取程序项目，例如https://github.com/Evil0ctal/Douyin_TikTok_Download_API和https://github.com/erma0/douyin，他们爬取的内容的基本都是默认采用文案命名视频的方式。但是读取这些视频，其实用其他方式比较麻烦。您的这个项目如果能支持本地化就能用比较好的方式来处理这种视频。由于适配了网页大小，甚至可以直接封装成APP。
