### ISSUE TITLE
现在这个问题可以解决吗？其他浏览器检测到页面内有视频会强制将视频全屏，并显示控制按钮，导致css和js都失效。

### ISSUE THREAD

**Issue by 1999-xinz** [zyronon/douyin#28]
现在这个问题可以解决吗？其他浏览器检测到页面内有视频会强制将视频全屏，并显示控制按钮，导致css和js都失效。
我也遇到了同样的困扰，需要在移动端的游览器内使用类douyin的播放，但是强制视频全屏导致很多东西都出不来了。

**Comment by zyronon** [comment]
无解。手机自带的浏览器都会这样

**Comment by lee29** [comment]
就是这个问题，https://github.com/wangyangexpo/Vue_TikTok   ，大佬能参考他的改一下吗，他的项目测试在safari不会强制视频全屏

**Comment by zyronon** [comment]
> 就是这个问题，https://github.com/wangyangexpo/Vue_TikTok ，大佬能参考他的改一下吗，他的项目测试在safari不会强制视频全屏

已修复
