### ISSUE TITLE
非常好的项目，期待完善，相关功能

### ISSUE THREAD

**Issue by bestNiu** [zyronon/douyin#38]
1、视频加载接口和评论
2、社区内容的真实实现

**Comment by zyronon** [comment]
> 1、视频加载接口和评论
> 2、社区内容的真实实现

没数据啊

**Comment by zyronon** [comment]
已经完善的七七八八了

**Comment by jackiechou1** [comment]
佬，为什么视频播放没有声音？

**Comment by elarber** [comment]
仓主能不能开通discussion模块啊，让大家可以讨论

**Comment by zyronon** [comment]
> 仓主能不能开通discussion模块啊，让大家可以讨论

开了

**Comment by zyronon** [comment]
> 佬，为什么视频播放没有声音？

默认是静音，不静音无法自动播放
