### ISSUE TITLE
Roadmap: 我觉得这个仓库可以调整的地方

### ISSUE THREAD

**Issue by Chanzhaoyu** [zyronon/douyin#46]
1、清理 console 和注释
2、将 Vue SFC 改为 setup 语法
3、修改 pinia 语法
4、迁移 typescript

**Comment by zyronon** [comment]
我前几天才把vuex换成pinia

慢慢来吧，旧代码太多了

**Comment by Chanzhaoyu** [comment]
> 我前几天才把vuex换成pinia
> 
> 慢慢来吧，旧代码太多了

慢慢来～
