### ISSUE TITLE
README 的动态图太擦边了，能不能换点健康一点的

### ISSUE THREAD

**Issue by sudo888samewick** [zyronon/douyin#52]
README 里面的动态图怎么全是妖艳骚货在跳舞……

**Comment by sudo888samewick** [comment]
![image](https://github.com/zyronon/douyin/assets/150644414/8a8ac137-4f97-401b-ac6a-164409b2ddc7)

**Comment by sudo888samewick** [comment]
本来想逛逛 github trending 开启元气满满的一天，没想到在github还能破戒，今天又要费钱买点牛奶补补了

**Comment by zyronon** [comment]
视频均来自抖音上的博主

图片均来自于小红书

均是合法合规的

**Comment by lizy0329-biubiubiu** [comment]
> 本来想逛逛 github trending 开启元气满满的一天，没想到在github还能破戒，今天又要费钱买点牛奶补补了

道友怕不是肾亏了？
