### ISSUE TITLE
Unable to scroll the page || 无法滚动页面

### ISSUE THREAD

**Issue by onaua** [zyronon/douyin#53]
### 注意：问题可以在浏览器的  无痕模式  下复现，而不是自己安装的其他插件或脚本导致的

1、描述
无论是在网页里还是localhost都无法往下滑，无法查看下一个视频，无法使用鼠标滚轮

### Note:  the problem can be reproduced in the browser's traceless mode, rather than being caused by other plugins or scripts installed by yourself

1. Description
No matter in the webpage or localhost, you can't slide down, you can't view the next video, and you can't use the mouse wheel.

**Comment by zyronon** [comment]
pc 浏览器上切到手机模式了没有？

**Comment by JustOptimize** [comment]
Can confirm, is is working only in mobile mode.
To enable it press `CTRL + SHIFT + I` or right click on the page and click "Inspect Element" and a side page will open; press on the laptop and mobile icon in the top left
![image](https://github.com/zyronon/douyin/assets/54294419/e3899666-3607-4061-b264-3101487763e6)
You can now use your mouse clicks to scroll like if it was a mobile phone
