### ISSUE TITLE
功能请求 | Feature request

### ISSUE THREAD

**Issue by hanzhiyuan515** [zyronon/douyin#59]
哥们 可以来个源码注释 或者文档吗?球球了

**Comment by zyronon** [comment]
谢谢，源码的确写的很乱，滑动的组件新代码和旧代码混合着

后面我会出一系列文章分享，目前正在准备中

**Comment by hanzhiyuan515** [comment]
> 谢谢，源码的确写的很乱，滑动的组件新代码和旧代码混合着
> 
> 后面我会出一系列文章分享，目前正在准备中

老哥 出了文章能不能喊我一下 感谢

**Comment by zyronon** [comment]
> > 谢谢，源码的确写的很乱，滑动的组件新代码和旧代码混合着
> > 后面我会出一系列文章分享，目前正在准备中
> 
> 老哥 出了文章能不能喊我一下 感谢

文章还在准备，别急，到时@你

**Comment by zyronon** [comment]
出了

**Comment by hanzhiyuan515** [comment]
感谢🙏

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月07日 10:17 |
| 收件人 | zyronon/douyin ***@***.***> |
| 抄送人 | Hzyy ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [zyronon/douyin] 功能请求 | Feature request (Issue #59) |

出了

**Comment by zyronon** [comment]
可以直接用 邮件回复？

**Comment by hanzhiyuan515** [comment]
可以的

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月07日 10:20 |
| 收件人 | zyronon/douyin ***@***.***> |
| 抄送人 | Hzyy ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [zyronon/douyin] 功能请求 | Feature request (Issue #59) |

可以直接用 邮件回复？
