### ISSUE TITLE
纯闲聊

### ISSUE THREAD

**Issue by shiwanmenghuxiahuashan** [zyronon/douyin#60]
好奇老哥 这个项目写了多久。有没有相关文章分享。想学习交流一下

**Comment by zyronon** [comment]
从 18 年就开始写啦，断断续续的下班后在家写，换算成全职时间我估计可能有 1，2 个月。

文章正在准备中...

**Comment by shiwanmenghuxiahuashan** [comment]
> 从 18 年就开始写啦，断断续续的下班后在家写，换算成全职时间我估计可能有 1，2 个月。
> 
> 文章正在准备中...

辛苦老哥，老哥发文章了，叫小弟一声，小弟去捧个场

**Comment by zyronon** [comment]
没有服务端，视频数据存在本地的json文件里面。

接口我已经定义好了，只是用第三方库拦截了请求返回本地的json

如果要接入服务端，只需要把拦截库注释掉，然后参照 本地json的格式返回就可以了

**Comment by zyronon** [comment]
> 这有服务端没，视频是存在本地还是两个都存
没有服务端，视频数据存在本地的json文件里面。

接口我已经定义好了，只是用第三方库拦截了请求返回本地的json

如果要接入服务端，只需要把拦截库注释掉，然后参照 本地json的格式返回就可以了

**Comment by zyronon** [comment]
> 这有服务端没，视频是存在本地还是两个都存

没有服务端，视频数据存在本地的json文件里面。

接口我已经定义好了，只是用第三方库拦截了请求返回本地的json

如果要接入服务端，只需要把拦截库注释掉，然后参照 本地json的格式返回就可以了

**Comment by zyronon** [comment]
> 这有服务端没，视频是存在本地还是两个都存

我不是做java的，不过我看到一个项目：https://gitee.com/dromara/dy-java。我没用过，你有用的可以看看

**Comment by coracoo** [comment]
老哥会出docker版本吗，自己试了一下写dockerfile一直没成功

**Comment by zyronon** [comment]
我现在不会docker。后面有空了学习下。如果你会弄的话，可以提 pr

**Comment by zyronon** [comment]
> 老哥会出docker版本吗，自己试了一下写dockerfile一直没成功


我现在不会docker。后面有空了学习下。如果你会弄的话，可以提 pr

**Comment by coracoo** [comment]
> > 老哥会出docker版本吗，自己试了一下写dockerfile一直没成功
> 
> 
> 
> 
> 
> 我现在不会docker。后面有空了学习下。如果你会弄的话，可以提 pr
> 
> 
> 
> 

npm22支持吗？一直报esm的错误

**Comment by zyronon** [comment]
> npm22支持吗？一直报esm的错误

node 22吗？没试过

我本地用的18

启动时是会报esm错误，可以先忽略

**Comment by Delay-n-days** [comment]
美女很漂亮，我很喜欢

**Comment by rookie-luochao** [comment]
> 老哥会出docker版本吗，自己试了一下写dockerfile一直没成功

前端dockerfile很简单，可以看下我这个项目，前端容器化热门文章基本上看得到我发的那篇
https://github.com/rookie-luochao/openapi-ui

**Comment by rookie-luochao** [comment]
> 从 18 年就开始写啦，断断续续的下班后在家写，换算成全职时间我估计可能有 1，2 个月。
> 
> 文章正在准备中...

你这个项目，我是看着它星星疯涨啊，是上了趋势榜吧，星星飙升，我这个小项目都不知道怎么推广下
https://github.com/rookie-luochao/openapi-ui

**Comment by zyronon** [comment]
> 你这个项目，我是看着它星星疯涨啊，是上了趋势榜吧，星星飙升，我这个小项目都不知道怎么推广下 https://github.com/rookie-luochao/openapi-ui

哈哈，后面我出一篇怎么推广的文章，到时@你看看

**Comment by rookie-luochao** [comment]
来这个闲聊栏目下推广下自己的项目吧，一个好用的可集成到后端 web框架的 swagger/openapi UI，主要是提升接口阅读和测试使用体验，我觉得比swagger-ui 阅读起来舒服很多，欢迎提pr一起建设，也欢迎支持更多的后端 web 框架，里面对 docker, 前端docker自动化部署, 前端自动发布docker镜像，前端自动发布npm包做了很友好的支持，可以拿来作为学习使用，如果有帮助到你麻烦 star, fork支持一下
https://github.com/rookie-luochao/openapi-ui  核心包
https://github.com/rookie-luochao/go-openapi-ui  go框架包

**Comment by rookie-luochao** [comment]
> > 你这个项目，我是看着它星星疯涨啊，是上了趋势榜吧，星星飙升，我这个小项目都不知道怎么推广下 https://github.com/rookie-luochao/openapi-ui
> 
> 哈哈，后面我出一篇怎么推广的文章，到时@你看看

好的，谢谢大佬，记得艾特我

**Comment by zyronon** [comment]
> 
> 好的，谢谢大佬，记得艾特我

你去v 站发过没

**Comment by rookie-luochao** [comment]
> > 好的，谢谢大佬，记得艾特我
> 
> 你去v 站发过没

发过，但是和你这种有热度的比不了，主要上过阮一峰老师周刊，涨了200个星星，然后V站估计涨了大几十个星星还

**Comment by rookie-luochao** [comment]
> > 好的，谢谢大佬，记得艾特我
> 
> 你去v 站发过没

但是当时我还没有支持web框架，只是个工具页，后面一个多月，我把它做成npm包了， 然后做了 go 框架的支持，后面对新 node 框架也做个支持吧，难度不高，但是框架这么多，任务量不小

**Comment by rookie-luochao** [comment]
果然

> > 好的，谢谢大佬，记得艾特我
> 
> 你去v 站发过没

果然你这个项目冲上了github 趋势榜第一，估计短时间星星数要破万哦，趋势榜第一很猛的，还有余力

**Comment by coracoo** [comment]
哈哈哈，自荐来了，前排脸熟，大佬能加个联系方式指导一下前端的dockerfile吗？一直没成功。我做自媒体的，主要就是在github找项目推广，目标是nas和docker用户，大佬们有兴趣可以一起聊聊。

**Comment by rookie-luochao** [comment]
> 哈哈哈，自荐来了，前排脸熟，大佬能加个联系方式指导一下前端的dockerfile吗？一直没成功。我做自媒体的，主要就是在github找项目推广，目标是nas和docker用户，大佬们有兴趣可以一起聊聊。


> 哈哈哈，自荐来了，前排脸熟，大佬能加个联系方式指导一下前端的dockerfile吗？一直没成功。我做自媒体的，主要就是在github找项目推广，目标是nas和docker用户，大佬们有兴趣可以一起聊聊。

可以的哈，我邮箱发我你的微信，我加你，邮箱 1055120207@qq.com

**Comment by zyronon** [comment]
> 果然你这个项目冲上了github 趋势榜第一，估计短时间星星数要破万哦，趋势榜第一很猛的，还有余力

猛的一P，netlify直接给我刷欠费了，吓得我赶紧把vercel都下了，现在只提供github pages地址了

![image](https://github.com/zyronon/douyin/assets/19986642/f10da61e-7793-4e72-8863-84e5c482f0d0)

**Comment by coracoo** [comment]
> > 果然你这个项目冲上了github 趋势榜第一，估计短时间星星数要破万哦，趋势榜第一很猛的，还有余力
> 
> 猛的一P，netlify直接给我刷欠费了，吓得我赶紧把vercel都下了，现在只提供github pages地址了
> 
> ![image](https://private-user-images.githubusercontent.com/19986642/326659543-f10da61e-7793-4e72-8863-84e5c482f0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDg5MDAsIm5iZiI6MTcxNDQ0ODYwMCwicGF0aCI6Ii8xOTk4NjY0Mi8zMjY2NTk1NDMtZjEwZGE2MWUtNzc5My00ZTcyLTg4NjMtODRlNWM0ODJmMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAzNDMyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmM2M2Y2JjMmFiNjYyYzY0NmE5Y2ZhZTU5Y2I1ZGVhMjUyZGQ3NTg5YTIxN2M1MDZlODRlZGU5MmVlMjQyNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._-YcUZ-FtmPrx7HtnCPT2OGXJuFs8XdZKb3Ft0oSMSE)

所以说瑟瑟是第一生产力

**Comment by rookie-luochao** [comment]
> > 老哥会出docker版本吗，自己试了一下写dockerfile一直没成功
> 
> 我现在不会docker。后面有空了学习下。如果你会弄的话，可以提 pr

我给你提一个docker的pr吧，你申请个 github token 放项目下面，可以私聊沟通一下，我邮箱 1055120207@qq.com

**Comment by rookie-luochao** [comment]
> > 果然你这个项目冲上了github 趋势榜第一，估计短时间星星数要破万哦，趋势榜第一很猛的，还有余力
> 
> 猛的一P，netlify直接给我刷欠费了，吓得我赶紧把vercel都下了，现在只提供github pages地址了
> 
> ![image](https://private-user-images.githubusercontent.com/19986642/326659543-f10da61e-7793-4e72-8863-84e5c482f0d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDg5MDEsIm5iZiI6MTcxNDQ0ODYwMSwicGF0aCI6Ii8xOTk4NjY0Mi8zMjY2NTk1NDMtZjEwZGE2MWUtNzc5My00ZTcyLTg4NjMtODRlNWM0ODJmMGQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAzNDMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YzA3NGY3NDVkMzBlOTgzODJhODZmYjQ4MWRhZWU1MjU5ZTM3MzMzNzk2NjliOGY0OGVjNzcwZDUwOTg4MTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gapz8tCcFVVPwqzzMDSFZapEnvBVwsQg23zks4tB4TE)

我擦，vercel这些流量用完了，会自动扣费吗？不会发提醒要你买流量吗？

**Comment by zyronon** [comment]
> 我擦，vercel这些流量用完了，会自动扣费吗？不会发提醒要你买流量吗？

vercel还不知道，图上是netlify。

**Comment by rookie-luochao** [comment]
> > 我擦，vercel这些流量用完了，会自动扣费吗？不会发提醒要你买流量吗？
> 
> vercel还不知道，图上是netlify。

直接扣钱有点流氓了，至少提醒你充钱买流量才是合理的，直接流量花超了直接扣钱，很恶心人

**Comment by zyronon** [comment]
> 直接扣钱有点流氓了，至少提醒你充钱买流量才是合理的，直接流量花超了直接扣钱，很恶心人

有提醒。是免费账号，没往里面充钱，目前是欠了$55的账单

**Comment by HeartMaster** [comment]
才感受到纯美女的抖音比码农的抖音好看多了

**Comment by rookie-luochao** [comment]
> > 老哥会出docker版本吗，自己试了一下写dockerfile一直没成功
> 
> 我现在不会docker。后面有空了学习下。如果你会弄的话，可以提 pr

我已经提交了构建docker镜像的pr, 触发机制为打tag, 格式为：v0.0.1, v1.0.0等等，以v开头

**Comment by zyronon** [comment]
@rookie-luochao @coracoo docker 镜像已推送到ghcr了

```bash
# pull Docker image
docker pull ghcr.io/zyronon/douyin-vue:latest

# start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
```

**Comment by rookie-luochao** [comment]
> @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> 
> ```shell
> # pull Docker image
> docker pull ghcr.io/zyronon/douyin-vue:latest
> 
> # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> ```

镜像还需要开放成共有的，镜像默认是私有，需要点设置开放出来

**Comment by zyronon** [comment]
> 镜像还需要开放成共有的，镜像默认是私有，需要点设置开放出来

ok了，已改成public了

**Comment by coracoo** [comment]
> > @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> 
> > 
> 
> > ```shell
> 
> > # pull Docker image
> 
> > docker pull ghcr.io/zyronon/douyin-vue:latest
> 
> > 
> 
> > # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> 
> > docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> 
> > ```
> 
> 
> 
> 镜像还需要开放成共有的，镜像默认是私有，需要点设置开放出来

太棒了，点赞

**Comment by havelearned** [comment]
很湿滑，可以说一下语音通话是怎么实现的吗，思路是怎么样的。

**Comment by zyronon** [comment]
> 很湿滑，可以说一下语音通话是怎么实现的吗，思路是怎么样的。

指的是那个缩小和放大的UI吗？

**Comment by 11003** [comment]
大佬，能弱弱问一下，keepalive这个方法如何在Nuxt3使用呢？Nuxt3里没routes这个😂

```js
router.beforeEach((to, from) => {
  const baseStore = useBaseStore()
  //footer下面的5个按钮，对跳不要用动画
  const noAnimation = ['/', '/home', '/me', '/shop', '/message', '/publish', '/home/live', '/test']
  if (noAnimation.indexOf(from.path) !== -1 && noAnimation.indexOf(to.path) !== -1) {
    return true
  }

  const toDepth = routes.findIndex((v) => v.path === to.path)
  const fromDepth = routes.findIndex((v) => v.path === from.path)
  if (toDepth > fromDepth) {
    if (to.matched && to.matched.length) {
      const toComponentName = to.matched[0].components?.default.name
      baseStore.updateExcludeRoutes({ type: 'remove', value: toComponentName })
    }
  } else {
    if (from.matched && from.matched.length) {
      const fromComponentName = from.matched[0].components?.default.name
      baseStore.updateExcludeRoutes({ type: 'add', value: fromComponentName })
    }
  }
  // ...
  // 返回 false 以取消导航
  return true
})
```

**Comment by zhinianboke** [comment]
> @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> 
> ```shell
> # pull Docker image
> docker pull ghcr.io/zyronon/douyin-vue:latest
> 
> # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> ```

请问下只能是80端口吗，改成其他端口访问不了，服务器80端口被其他项目占用了

**Comment by rookie-luochao** [comment]
> > @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> > ```shell
> > # pull Docker image
> > docker pull ghcr.io/zyronon/douyin-vue:latest
> > 
> > # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > ```
> 
> 请问下只能是80端口吗，改成其他端口访问不了，服务器80端口被其他项目占用了

端口可以是任意端口都行，比如：8080，然后做域名解析的时候，监听域名的80端口，反向代理到你设置的8080端口
详情见：https://github.com/rookie-luochao/openapi-ui?tab=readme-ov-file#docker-deploy-support-env-variable-injection

**Comment by rookie-luochao** [comment]
> > @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> > ```shell
> > # pull Docker image
> > docker pull ghcr.io/zyronon/douyin-vue:latest
> > 
> > # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > ```
> 
> 请问下只能是80端口吗，改成其他端口访问不了，服务器80端口被其他项目占用了

给你顺便贴一段我写的nginx反向代理配置吧

server {
	    listen       80;
	    server_name  www.xxx.com;
	    return 301 https://$server_name$request_uri;
	    location / {	        
	        proxy_set_header Host $proxy_host;
	        proxy_set_header X-Real-IP $remote_addr;
	        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

	        proxy_buffering on;
		   proxy_buffers 8 16k;
		   proxy_buffer_size 16k;

	        # 启用 Gzip 压缩
	        gzip on;
	        gzip_min_length 1000;
	        gzip_types text/plain application/javascript application/x-javascript text/javascript text/xml text/css;
	        # 选择性地设置 Gzip 压缩等级
	        gzip_comp_level 6;
	        # 启用 Gzip 静态文件预压缩
	        gzip_static on;
	
	        # 启用 Gzip 压缩代理响应
	        proxy_http_version 1.1;
	        proxy_set_header Upgrade $http_upgrade;
	        proxy_set_header Connection 'upgrade';

	        proxy_pass http://127.0.0.1:8080;
	    }
	}

**Comment by zhinianboke** [comment]
> > > @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> > > ```shell
> > > # pull Docker image
> > > docker pull ghcr.io/zyronon/douyin-vue:latest
> > > 
> > > # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > > docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > > ```
> > 
> > 
> > 请问下只能是80端口吗，改成其他端口访问不了，服务器80端口被其他项目占用了
> 
> 端口可以是任意端口都行，比如：8080，然后做域名解析的时候，监听域名的80端口，反向代理到你设置的8080端口 详情见：https://github.com/rookie-luochao/openapi-ui?tab=readme-ov-file#docker-deploy-support-env-variable-injection

好的，感谢，我在试试

**Comment by rookie-luochao** [comment]
> > > > @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> > > > ```shell
> > > > # pull Docker image
> > > > docker pull ghcr.io/zyronon/douyin-vue:latest
> > > > 
> > > > # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > > > docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > > > ```
> > > 
> > > 
> > > 请问下只能是80端口吗，改成其他端口访问不了，服务器80端口被其他项目占用了
> > 
> > 
> > 端口可以是任意端口都行，比如：8080，然后做域名解析的时候，监听域名的80端口，反向代理到你设置的8080端口 详情见：https://github.com/rookie-luochao/openapi-ui?tab=readme-ov-file#docker-deploy-support-env-variable-injection
> 
> 好的，感谢，我在试试

如果不做域名解析，id地址 + 8080端口既可以访问到

**Comment by zhinianboke** [comment]
> > > > > @rookie-luochao @coracoo docker 镜像已推送到ghcr了
> > > > > ```shell
> > > > > # pull Docker image
> > > > > docker pull ghcr.io/zyronon/douyin-vue:latest
> > > > > 
> > > > > # start container, nginx reverse proxy custom port, for example: docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > > > > docker run -d -p 80:80 ghcr.io/zyronon/douyin-vue:latest
> > > > > ```
> > > > 
> > > > 
> > > > 请问下只能是80端口吗，改成其他端口访问不了，服务器80端口被其他项目占用了
> > > 
> > > 
> > > 端口可以是任意端口都行，比如：8080，然后做域名解析的时候，监听域名的80端口，反向代理到你设置的8080端口 详情见：https://github.com/rookie-luochao/openapi-ui?tab=readme-ov-file#docker-deploy-support-env-variable-injection
> > 
> > 
> > 好的，感谢，我在试试
> 
> 如果不做域名解析，id地址 + 8080端口既可以访问到

弄好了，感谢

**Comment by or6521** [comment]
求问各位大佬，有什么办法方便的加一个视频进来吗。我在pcweb版抖音上没找到作者说的接口。。。

**Comment by zyronon** [comment]
> 求问各位大佬，有什么办法方便的加一个视频进来吗。我在pcweb版抖音上没找到作者说的接口。。。

https://www.douyin.com/aweme/v1/web/tab/feed 是推荐接口

https://www.douyin.com/aweme/v1/web/aweme/post/ 是指定用户的视频列表

😋😋😋

我项目的前6条数据，放在这个文件里面 https://github.com/zyronon/douyin/blob/master/src/assets/data/posts6.json

后面的数据，放在这个文件里面 https://github.com/zyronon/douyin/blob/master/public/data/videos.json

你想加视频，参考上面文件里面数据的格式，复制粘贴一条就行了。

**Comment by 15538567895** [comment]
大佬能出个结构图吗？比如想替换视频、替换资料之类的，要替换的文件在哪里

**Comment by zyronon** [comment]
> 大佬能出个结构图吗？比如想替换视频、替换资料之类的，要替换的文件在哪里

看上一条回复

**Comment by zyronon** [comment]
> https://dy.ttentau.top/#/me “我”这个界面随便点开一个私密、喜欢、收藏下面的视频，再返回还是会一直在播放这个视频，如果点开过多个，那声音就一直叠加了

收到

**Comment by tiandeli** [comment]
大哥 牛逼 回头研究下代码

**Comment by sqd1998** [comment]
牛的 点赞

**Comment by PandaNetworkCN** [comment]
> > 求问各位大佬，有什么办法方便的加一个视频进来吗。我在pcweb版抖音上没找到作者说的接口。。。
> 
> https://www.douyin.com/aweme/v1/web/tab/feed 是推荐接口
> 
> https://www.douyin.com/aweme/v1/web/aweme/post/ 是指定用户的视频列表
> 
> 😋😋😋
> 
> 我项目的前6条数据，放在这个文件里面 https://github.com/zyronon/douyin/blob/master/src/assets/data/posts6.json
> 
> 后面的数据，放在这个文件里面 https://github.com/zyronon/douyin/blob/master/public/data/videos.json
> 
> 你想加视频，参考上面文件里面数据的格式，复制粘贴一条就行了。


你好， Docker里怎么找到 posts6.json和videos.json这两个配置文件？

**Comment by zyronon** [comment]
@PandaNetworkCN docker 我就不懂了😁，网友提的pr

**Comment by luul11** [comment]
我是docker 部署的，无论是posts.json还是videos.json  都没找到6 个示例视频，也没找到 post6.json

目录在
var
lib
docker
overlay2
6cc557bb93f4d714e921829f36a795232b3ab991fe110869e99d650809afa7c4
merged
app
data

**Comment by CHAT-00001** [comment]
> > 从 18 年就开始写啦，断断续续的下班后在家写，换算成全职时间我估计可能有 1，2 个月。
> > 文章正在准备中...
> 
> 你这个项目，我是看着它星星疯涨啊，是上了趋势榜吧，星星飙升，我这个小项目都不知道怎么推广下 https://github.com/rookie-luochao/openapi-ui

我是在抖音看到人家推这个项目，才进来找到的

**Comment by rinvay** [comment]
为什么zip包下载不行？和git clone没差吧？

**Comment by mengdodo** [comment]
你这个项目应该是上了推荐，我在抖音和微信公众号文章都刷到了，没办法，先点个赞

**Comment by zyronon** [comment]
> 你这个项目应该是上了推荐，我在抖音和微信公众号文章都刷到了，没办法，先点个赞

曾经 github  trending 全球榜第一

**Comment by abcdedfdfasdfsa** [comment]
改了点东西，现在项目出现了很多这样的警告该怎么办？
[Vue warn]: The `compilerOptions` config option is only respected when using a build of Vue.js that includes the runtime compiler (aka "full build"). Since you are using the runtime-only build, `compilerOptions` must be passed to `@vue/compiler-dom` in the build setup instead.
- For vue-loader: pass it via vue-loader's `compilerOptions` loader option.
- For vue-cli: see https://cli.vuejs.org/guide/webpack.html#modifying-options-of-a-loader
- For vite: pass it via @vitejs/plugin-vue options. See https://github.com/vitejs/vite-plugin-vue/tree/main/packages/plugin-vue#example-for-passing-options-to-vuecompiler-sfc
