### ISSUE TITLE
功能请求 | 差的10%是视频列表没有插广告吗？

### ISSUE THREAD

**Issue by wumingluren** [zyronon/douyin#61]
1、描述
视频列表增加广告
  
2、这个功能解决了什么问题？
学习一下怎么插入广告在视频列表里

**Comment by zyronon** [comment]
哈哈哈哈，广告就和正常视频一样的呗

**Comment by wumingluren** [comment]
> 哈哈哈哈，广告就和正常视频一样的呗

哪怕是在用户视频列表页刷视频都会突然刷出来广告。

**Comment by zyronon** [comment]
> > 哈哈哈哈，广告就和正常视频一样的呗
> 
> 哪怕是在用户视频列表页刷视频都会突然刷出来广告。

可以这么理解

视频列表是一个数组，一开始里面只有5条数据  
当你往下滑动的时候，接口去请求更多的数据  
这个接口可以返回接下来的5条数据，也可以返回一条广告+加4条正常的数据
