### ISSUE TITLE
功能请求 | 有考虑过写返回值的接口吗

### ISSUE THREAD

**Issue by Rokiers** [zyronon/douyin#65]
1、描述
单独写一个model文件，对axois的返回值进行描述，后面方便使用，就不用用any规范了，使用起来也挺方便的
  
2、这个功能解决了什么问题？
写好后，不用回头查看返回值的类型

3，还有个小问题，作者你这个接口是自己设计的吗，我自己写项目的时候用mock，总是不知道接口怎么搞，最后弄得一塌糊涂，你这个接口写的有模有样的，跟真的一样，有什么诀窍吗

**Comment by zyronon** [comment]
可以用ts定义好返回值类型，我这个项目一开始是js的，最近才慢慢的改成ts的。好多变量、方法还没来得及加类型定义

我没设计数据结构，因为数据来源于抖音啊，打开抖音pc的web版，找到请求把内容复制下来就行了，我保存到了本地的一个json文件里面

接口设计？没什么诀窍，感觉就是工作中调接口调多了有经验了，非要说设计，接口根据项目需要设计呗，哪个地方需要请求数据就写一个...

"跟真的一样"，因为我用axios真的定义了一些接口，然后用一个库把 所有请求拦截了，返回本地保存的json数据。如果把拦截库注释掉，那些请求是真的会发送的...

**Comment by Rokiers** [comment]
多谢指教

**Comment by wsbblyy** [comment]
> "跟真的一样"，因为我用axios真的定义了一些接口，然后用一个库把 所有请求拦截了，返回本地保存的json数据。如果把拦截库注释掉，那些请求是真的会发送的...

要注释什么可以发送真的请求, 注释//startMock()吗

**Comment by zyronon** [comment]
对呀



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月02日 20:31 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [zyronon/douyin] 功能请求 | 有考虑过写返回值的接口吗 (Issue #65) |

"跟真的一样"，因为我用axios真的定义了一些接口，然后用一个库把 所有请求拦截了，返回本地保存的json数据。如果把拦截库注释掉，那些请求是真的会发送的...

要注释什么可以发送真的请求, 注释//startMock()吗
