### ISSUE TITLE
求教 | npm run dev报错

### ISSUE THREAD

**Issue by wenbo0O** [zyronon/douyin#70]
大家都是怎么启动成功的啊，我的本地环境和报错如下图

![image](https://github.com/zyronon/douyin/assets/37663902/addeb24f-bdfe-4167-9058-596b68b08cb3)
![image](https://github.com/zyronon/douyin/assets/37663902/942360a1-0c50-4bd9-aa39-39eab2c6a468)
![image](https://github.com/zyronon/douyin/assets/37663902/1dcb21fe-ae1d-4820-b605-8c92208ea27f)

尝试按照[https://vitejs.dev/guide/troubleshooting.html#cjs](https://vitejs.dev/guide/troubleshooting.html#cjs)还是不行
![image](https://github.com/zyronon/douyin/assets/37663902/7e2ca854-cfc9-44d9-8f2c-78fbbb4cf00b)

**Comment by zyronon** [comment]
本项目必须用 git 命令 clone 下来才能正常运行，直接下载zip包是无法运行的

如果 git clone github 的地址网速太慢的话，可以使用gitee的地址，代码是同步的

git clone https://gitee.com/zyronon/douyin.git

**Comment by cngoodgod** [comment]
好复杂不会。有没有手机端APP呀
