### ISSUE TITLE
仓库太大了，public/images 图片能弄成JPG? 112M的PNG图片

### ISSUE THREAD

**Issue by AZmake** [zyronon/douyin#76]
public/images 图片能弄成JPG? 112M的PNG图片

**Comment by zyronon** [comment]
只是名字是png而已，我写脚本批量下载时写的固定后缀名

图片内容我已经压缩过了，没法再缩小了，除非删除内容

**Comment by AZmake** [comment]
个人建议感觉图片尺寸可以更小一点，没必要那么高清
