### ISSUE TITLE
想问大佬个问题

### ISSUE THREAD

**Issue by super117893344p** [zyronon/douyin#78]
vue3官方似乎不支持移动端开发吧 ,  你用的是vue Native 框架吗 ,  还有你那句 必须git命令clone下来才能运行，下载zip包是无法运行的   这是为什么呢

**Comment by super117893344p** [comment]
还有你这些视频数据是怎么拿到接口的呀

**Comment by rookie-luochao** [comment]
> 还有你这些视频数据是怎么拿到接口的呀

写的静态数据配置，可以理解为抓的视频链接写死在项目里

**Comment by zyronon** [comment]
> vue3官方似乎不支持移动端开发吧 , 你用的是vue Native 框架吗 , 还有你那句 必须git命令clone下来才能运行，下载zip包是无法运行的 这是为什么呢

不知道，有好几个网友反馈，下载下来无法运行。

视频数据： 在抖音官方的web版，打开控制台就可以看到接口了

**Comment by super117893344p** [comment]
![图片](https://github.com/zyronon/douyin/assets/129602465/acfac156-a1a6-48e1-b2c4-325314410ceb)
 你这如果是uniapp打包的话, 怎么没见manifest,json文件呢

**Comment by zyronon** [comment]
uniapp有个 5+app的功能，可以把 静态页面打包成 app
