### ISSUE TITLE
作者可以添加一个文档说明如何将视频链接替换为自己设置的url吗

### ISSUE THREAD

**Issue by Yiyun0422** [zyronon/douyin#82]
看了一下作者的代码，工程量确实大，作者辛苦了。但是还是希望作者能添加一份文档描述一下视频处在哪个文件里，如何进行修改。这样用户可以将视频链接替换为自己设置的视频，貌似更有意思，希望作者能考虑一下

**Comment by zyronon** [comment]
项目的前6条数据，放在这个文件里面 https://github.com/zyronon/douyin/blob/master/src/assets/data/posts6.json

后面的数据，放在这个文件里面 https://github.com/zyronon/douyin/blob/master/public/data/videos.json

你想加视频，参考上面文件里面数据的格式，复制粘贴一条就行了。

后续会添加一个说明文档
