### ISSUE TITLE
切换到下一个视频后视频并不会自动播放

### ISSUE THREAD

**Issue by kola-web** [zyronon/douyin#85]
### 注意：请确认问题可以在浏览器的  无痕模式  下复现，而不是自己安装的其他插件或脚本导致的

1、描述
在微信中打开，切换到下一个视频后视频并不会自动播放，且会出现如下图中的报错，而且视频中间并没有出现开始播放按钮
经测试在ios safari浏览器中也会出现下面截图中的错误，导致视频暂停

2、截图
可以直接按Ctrl + V 复制在这里（复制成功后会显示一串地址）
![image](https://github.com/zyronon/douyin/assets/46446884/5b04e4c0-4d76-4c85-b6b0-f9ddcaf145ac)

**Comment by zyronon** [comment]
ios上是会出现这个问题

原因是新生成的video 标签无法在未静音的情况下自动播放，即使已经产生过交互了

在考虑另一种实现方式，即滑动后不生成新的video标签，而是不断的移动video到合适的位置

**Comment by kola-web** [comment]
> ios上是会出现这个问题
> 
> 原因是新生成的video 标签无法在未静音的情况下自动播放，即使已经产生过交互了
> 
> 在考虑另一种实现方式，即滑动后不生成新的video标签，而是不断的移动video到合适的位置

感谢您的思路，我去尝试下

**Comment by kola-web** [comment]
多谢您的提点，问题顺利解决了
