### ISSUE TITLE
问题报告 | 按住进度条拖动事件冲突

### ISSUE THREAD

**Issue by osakey** [zyronon/douyin#87]
1、描述
按住时常进度条，会跟切换顶部tab，冲突，还有右边也是，

2、截图

**Comment by zyronon** [comment]
兼容问题，因为我把swiper的事件从原来的touch事件，修改为pointer事件了。
但其他地方滑动还是用的touch事件，限止touch事件并不能阻止pointer事件传播，所以就会一起动。
为什么要用pointer事件？目前我在掘金写一系列关于这个项目的文章，每天都有人点star，用了pointer事件在PC上可以滑动了，可以预览大部分的功能。
但会导致的设置了overflow:auto的div，无法触发Pointer事件，我原来的首页刷新都失效了
所以后面等项目热度低了之后，我后面会把pointer事件改回touch事件，那样所有功能在手机上都能正常使用了，只是PC上无法正常用，现在还不打算改

**Comment by ddpopbb3** [comment]
@zyronon 老哥可以大致描述下修改的思路吗？我让Agent提PR
