### ISSUE TITLE
功能请求 | 播放网盘视频

### ISSUE THREAD

**Issue by tin607** [zyronon/douyin#93]
1、描述
希望可以播放私有网盘中的视频，支持webdav就行了。
  
2、这个功能解决了什么问题？
喜欢的抖音视频不想点关注，怕被人发现，但是下载下来了，又不能像抖音那样播放。

**Comment by bot223** [comment]
+1

**Comment by luul11** [comment]
这种估计要自己开发了，作者貌似用的是抖音的视频接口

**Comment by zyronon** [comment]
https://github.com/zyronon/douyin/issues/123

https://github.com/zyronon/douyin/issues/118
