### ISSUE TITLE
希望就一下几点进行优化，提升最佳实践

### ISSUE THREAD

**Issue by yangnuowei88** [zyronon/douyin#94]
1. 大量重复性引用（考虑提取为公共文件，或者利用vite插件自动导入）
```javascript
import { useRouter } from 'vue-router'
import { computed, onDeactivated, onMounted, onUnmounted, reactive } from 'vue'
```
2. 没有用TS,可否直接去掉算了
```javascript
<script setup lang="ts">
```
3. 事件钩子可以用一个方法进行保障聚合在一起吗？
4.  处理函数是否应该弄个统一的命名空间聚合起来，感觉太分散了

**Comment by 211277729** [comment]
没必要，这重复性引用是vue内置的，用到的就引用，你弄成公共的，用不到的也给引用进来，反而性能差

**Comment by zyronon** [comment]
1这些是ide自动导入的，要用这个hook就需要导入，本身vue直接导出来直接就可以用了，再包一层感觉有点多余   
2可以
3你是指onDeactivated, onMounted, onUnmounted,这种方法聚合成一个方法吗？可以但没必要，这样写怪怪的....感觉像vue2写法   
4单个方法导入，用到哪个导那个，特意这样做的，因为这样便于打包器分析和优化未使用的代码。
