### ISSUE TITLE
怎么把视频换成自己的接口

### ISSUE THREAD

**Issue by QQand77** [zyronon/douyin#97]
怎么把视频换成自己的接口，需要改动哪个文件

**Comment by zyronon** [comment]
![image](https://github.com/user-attachments/assets/a84eb5ee-0e26-4e42-922f-a12888aadd01)

如果你想直接换视频，那就把图上的json文件的数据换掉就行

如果你想以接口的方式展示后端的视频，那把startMock 方法注释掉，然后实现api文件下面对应的接口，返回格式和json文件一样就行了
